name: README Display

on:
  push:
    paths:
      - 'Readme.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Update README
        run: |
          # This workflow ensures the README.md is properly displayed on GitHub
          echo "README.md updated successfully!" 